apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: storefront
data:
  nginx.conf: |
    events {}

    http {
      upstream web {
        server web-service:8000;
      }

      server {
        listen 80;

        location / {
          proxy_pass http://web;
        }
      }
    }